import type { Metadata, Viewport } from "next";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import { siteConfig } from "@/data/site";
import { fontVariables } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: "AQVION LABS — AI, Automation & Software Engineering",
    /* Inner pages supply only their own name. */
    template: "%s — AQVION LABS",
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  keywords: [
    "artificial intelligence",
    "AI engineering",
    "intelligent automation",
    "software engineering",
    "data platforms",
    "cloud infrastructure",
    "digital products",
  ],
  authors: [{ name: siteConfig.name }],
  creator: siteConfig.name,
  publisher: siteConfig.name,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: "AQVION LABS — AI, Automation & Software Engineering",
    description: siteConfig.description,
    /* The image itself is generated by app/opengraph-image.tsx. */
  },
  twitter: {
    card: "summary_large_image",
    title: "AQVION LABS — AI, Automation & Software Engineering",
    description: siteConfig.description,
    /* TODO(brand): add the official @handle once the account exists. */
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  formatDetection: { telephone: false, address: false, email: false },
};

export const viewport: Viewport = {
  themeColor: "#04060d",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang={siteConfig.locale} className={fontVariables} suppressHydrationWarning>
      <head>
        {/* Arms the hero activation sequence before the first paint.

            The sequence is opt-IN: styles/hero.css only animates while this
            attribute is present, so with no JavaScript, a returning visitor, or
            reduced motion, the hero renders complete and immediately. It plays
            once per browser session, and every step is wrapped so that a
            storage failure (private browsing, blocked cookies) degrades to
            "play it" rather than throwing. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{
if(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
var seen=false;try{seen=sessionStorage.getItem('aqvion.hero.intro')==='1';sessionStorage.setItem('aqvion.hero.intro','1')}catch(e){}
if(!seen)document.documentElement.setAttribute('data-hero-intro','run')
}catch(e){}})();`,
          }}
        />

        {/* Scroll reveals start at opacity 0 and are resolved by JavaScript.
            Without it the content would never appear, so the hidden state is
            cancelled outright. */}
        <noscript>
          <style>{`[data-reveal]{opacity:1!important;transform:none!important}`}</style>
        </noscript>
      </head>
      <body className="min-h-dvh antialiased">
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:rounded-md focus:border focus:border-border-strong focus:bg-surface-elevated focus:px-4 focus:py-2 focus:text-sm focus:text-foreground"
        >
          Skip to content
        </a>

        <Navbar />

        {/* The navbar is fixed, so the document flow is offset here rather than
            inside every page. */}
        <main id="main" className="pt-[var(--nav-height)]">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
