/**
 * Company-level facts and copy.
 *
 * CONTENT RULE — nothing in this file may be invented. Clients, revenue,
 * awards, certifications, partnerships, statistics and case studies are added
 * only from information supplied by AQVION LABS. Anything not yet supplied is
 * marked with `PLACEHOLDER` so it is impossible to ship by accident.
 */

/** Marks a value that is waiting on real company information. */
export const PLACEHOLDER = "PLACEHOLDER" as const;

export const siteConfig = {
  name: "AQVION LABS",
  shortName: "AQVION",
  tagline: "CODE • CREATE • INNOVATE",

  /**
   * One-sentence positioning. Describes capability, claims no outcomes.
   */
  positioning:
    "AQVION LABS engineers intelligent systems — artificial intelligence, automation, software, data platforms and cloud infrastructure — for organizations building something serious.",

  description:
    "AQVION LABS engineers intelligent systems, AI solutions, automation, software, data platforms, and digital products for ambitious organizations.",

  /** TODO(brand): replace once the production domain is registered. */
  url: "https://aqvionlabs.com",

  locale: "en",

  /** Contact details — awaiting real values from the company. */
  contact: {
    email: PLACEHOLDER,
    phone: PLACEHOLDER,
    addressLines: [PLACEHOLDER],
  },

  /** Social profiles — awaiting real handles. Empty `href` renders as inert. */
  social: [
    { label: "LinkedIn", href: PLACEHOLDER },
    { label: "GitHub", href: PLACEHOLDER },
    { label: "X", href: PLACEHOLDER },
  ],
} as const;

/** True when a data value is still a placeholder rather than real content. */
export function isPlaceholder(value: string): boolean {
  return value === PLACEHOLDER;
}

export const brandAssets = {
  /**
   * The official mark, exactly as supplied. This file is the source of truth:
   * it is never redrawn, re-typeset, re-proportioned or replaced with an icon.
   */
  master: "/brand/aqvion-mark.png",
  /** Identical artwork with the black field knocked out, for compositing. */
  masterAlpha: "/brand/aqvion-mark-alpha.png",
  /**
   * Delivery size used across the interface. 512px is comfortably above 3x for
   * every place the mark appears in chrome, and keeps next/image's source
   * decode cheap. All derivatives are generated by scripts/gen-brand-assets.mjs.
   */
  mark: "/brand/aqvion-mark-512.png",
  markMedium: "/brand/aqvion-mark-256.png",
  markSmall: "/brand/aqvion-mark-96.png",
  /** The mark is square by construction. */
  intrinsicSize: 512,
  alt: "AQVION LABS",
} as const;
